version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy/
    overwrite: yes

permissions:
  - object: /home/ubuntu/deploy/
    pattern: "**"
    owner: root
    group: root
    mode: 777

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: root