version: '3.8'

services:
#  backend:
#    image: backend:latest
#    ports:
#      - 8080:8080
#    depends_on:
#      - mysql

  mysql:
    image: library/mysql
    platform: linux/amd64
    volumes:
      - db_datas:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=changeme
      - TZ= Asia/Seoul
    ports:
      - 13306:3306

  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_boot
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 16379:6379

volumes:
  db_datas:
