version: '3.8'

services:
  backend:
    image: backend:latest
    environment:
    - LOGSTASH_HOST_NAME=localhost
    - LOGSTASH_HOST_PORT=50000
    ports:
      - 8080:8080
    depends_on:
      - mysql
    volumes:
      - log_datas:/logs

  mysql:
    image: mysql:8.0.32
    container_name: art-mysql
    platform: linux/amd64
    volumes:
      - db_datas:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=art
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=changeme
      - TZ= Asia/Seoul
    ports:
      - 13306:3306
  redis:
    image: redis:7.0-alpine
    command: redis-server --port 6379
    container_name: art-redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 16379:6379

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.6.2
    container_name: art-filebeat
    volumes:
      - ./filebeat-template.yml:/usr/share/filebeat/filebeat-template.yml
      - log_datas:/logs
    ports:
      - 5044:5044
    depends_on:
      - backend

volumes:
  db_datas:
  log_datas: