version: '3.8'

services:
#  backend:
#    image: backend:latest
#    ports:
#      - 8080:8080
#    depends_on:
#      - mysql

  mysql:
    image: mysql:8.0.32
    container_name: codebase-mysql
    platform: linux/amd64
    volumes:
      - db_datas:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=mega123!
      - TZ= Asia/Seoul
    ports:
      - 13306:3306
  redis:
    image: redis:7.0-alpine
    command: redis-server --port 6379
    container_name: codebase-redisvar
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 16379:6379
volumes:
  db_datas:
