spring:
  profiles:
    active: dev # default profile
    include:
      - mysql
      - redis
      - jwt
      - flyway
      - oauth
      - s3

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  config: classpath:log/log4j2-${spring.profiles.active}.xml
  level:
    jdbc:
      sqlonly: off
      sqltiming: info
      resultsettable: off
      audit: off
      resultset: off
      connection: off

#logging:
#  level:
#    com.example : DEBUG