spring:
  profiles:
    active: default
    include:
      - mysql
      - redis
      - jwt
      - flyway

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com.example : DEBUG