
---
spring:
  config:
    activate:
      on-profile:
        - dev

elasticsearch:
  host: ENC(h2zwdrTTT3YDNlIIZd+EHLf+TZn7iotT1h6LNTkft01UP28M2E+hJ+0WNGVjQmkI)
  username: ENC(gOeYrnq0KVLNP77ppWKArcqDQwcR8goFCcdEqSha1rk=)
  password: ENC(lIIhEBJoZNN2kMMsK+WyDsQ2t+zpLiL4MFQVuDgX8d936/pfR3F+zAXH5G7bJWvQ)

---
spring:
  config:
    activate:
      on-profile:
        - prod

elasticsearch:
  host: ENC(KzcIkzOTU9d6fqJjc/XbLPzc3X7ozoc4PX/u6hdAdR+m2DN+vp0Shu8xnJBq9Gdg)
  username: ENC(nur3iI3FgOXRqYtnDNoDlXldz6Fc1uL5d+VwhoP+2mA=)
  password: ENC(yoyeZ+8Gr4T6OsI6nKcUsM7q3w0rMKa6Dlx3VTwyzrg=)