spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(ZiOtpzcNYDTEYDVViIltu1uAqCTsf1xG3sc0g7e2ROCM8uhpEywrfikswFBX3aSI)
    password: ENC(v+lkov2t0W09HB7VKD5th0hvyvl6SeZpcVRwY+LJ8QspYsAzzuWIAnoiif7SddpS)
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory # Use SSL
          auth: true # Use AUTH
          timeout: 5000 # Timeout
          starttls:
            enable: true # Use STARTTLS
            required: true # Use STARTTLS

mail:
  callback.url: http://localhost:3000/user/auth/confirm

---
spring:
  config:
    activate:
      on-profile:
        - dev

mail:
  callback.url: https://dev.artscope.kr/user/auth/confirm


---

spring:
  config:
    activate:
      on-profile:
        - prod

mail:
  callback.url: https://artscope.kr/user/auth/confirm
