spring:
  profiles:
    active: default # default profile
    include:
      - mysql
      - redis
      - jwt
      - flyway
      - oauth
      - s3

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com.example : DEBUG

---
spring:
  config:
    activate:
      on-profile:
        - default

api:
  oauth2-redirect-uri: http://localhost:3000/oauth2/success

---
spring:
  config:
    activate:
      on-profile:
        - prod

api:
    oauth2-redirect-uri: https://artfe.megabrain.kr/oauth2/success