cloud:
  aws:
    credentials:
      access-key: ENC(BaJY14CYuh84i3vKLTTdwb1c6GhgFXREr5EgoQkB5VPBVCIAuhvJtNY8h6k4kzah)
      secret-key: ENC(aeDewy3SoLkkdSVM8fTFroIAZcqimch0RFg1aGt2anf7DSt5AMKr/RlnfdBiVfUpTwDQ03zeBXtCDvojdas8wQ==)
    region:
      static: ap-northeast-2
    s3:
      bucket: media-xi-art-storage
      root-dir: "prod/"
    stack:
      auto: false
    file-dir: classpath:/static/files

spring:
  servlet:
    multipart:
        enabled: true
        max-file-size: 100MB
        max-request-size: 100MB
        resolve-lazily: true  # Error Handling

app:
  file-count: 8

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

