elasticsearch:
  host: ENC(KzcIkzOTU9d6fqJjc/XbLPzc3X7ozoc4PX/u6hdAdR+m2DN+vp0Shu8xnJBq9Gdg)
  username: ENC(nur3iI3FgOXRqYtnDNoDlXldz6Fc1uL5d+VwhoP+2mA=)
  password: ENC(yoyeZ+8Gr4T6OsI6nKcUsM7q3w0rMKa6Dlx3VTwyzrg=)