cloud:
  aws:
    credentials:
      access-key: AKIAX3DJSUC27ZQJR46I
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: media-xi-art-storage
    stack:
      auto: false
    file-dir: classpath:/static/files

spring:
  servlet:
    multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB
        resolve-lazily: true  # Error Handling

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error