spring:
  profiles:
    active: local # default profile
    include:
      - mysql
      - redis
      - jwt
      - flyway
      - oauth
      - s3
      - mail
      - es
      - admin

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  servlet:
    encoding:
      charset: UTF-8

  tomcat:
    remote-ip-header: x-forwarded-for # nginx proxy
    protocol-header: x-forwarded-proto # nginx proxy
  forward-headers-strategy: native # nginx proxy

service:
  key: ENC(9zqDsgzBumBBJFnUI4WKLd8dJJWShdC1RAwwmDB/dRzneBDRCLJaxcMOI6k4bKNB7Q77+SzL+vluSmBmAXpMh8TUlrm10MYGfCiLfWmlWM6QMhNKDMa9F1o/+wAppUoGWG9e/Iv82D04cvExrD1aWg==)

logging:
  config: classpath:log/log4j2-${spring.profiles.active}.xml
#  level:
#    jdbc:
#      sqlonly: off
#      sqltiming: info
#      resultsettable: info
#      audit: off
#      resultset: off
#      connection: off

#---
#spring:
#  config:
#    activate:
#      on-profile:
#        - prod
#
#logging:
#  level:
#    jdbc:
#      resultsettable: off

#logging:
#  level:
#    com.example : DEBUG

webhook:
  url: ENC(zFU82/rmw5XeGwXpF3faHzvyU4JSiMJPFKkLQpWuaGmA4LfXmtsu/UKBUJ8eKRiBHGsIS+hGG9/QCw8VDiGqSPyO+cSceqNvg8kfw4FTVOgSJkVBAiVm4G/HA/8KG3mDHRHQ9yeeMuMQCV/o8zPhFX7PPALZCZfcQWr33MZ6E3w3PvDy2zy5tmWU3VipP2gW)

build:
  info: ${BUILD_INFO:native}

sentry:
  dsn: ${SENTRY_DSN}
  exception-resolver-order: -2147483647