spring:
  profiles:
    active: default
    include:
      - mysql
      - jwt
      - flyway

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


logging:
  level:
    kr.megabrain : DEBUG