spring:
  profiles:
    active: default
    include:
      - psql
      - jwt
      - flyway
      - redis

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


logging:
  level:
    kr.megabrain : DEBUG