spring:
  profiles:
    active: local # default profile
    include:
      - mysql
      - redis
      - jwt
      - flyway
      - oauth
      - s3
      - mail

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  servlet:
    encoding:
      charset: UTF-8

  tomcat:
    remote-ip-header: x-forwarded-for # nginx proxy
    protocol-header: x-forwarded-proto # nginx proxy
  forward-headers-strategy: native # nginx proxy

service:
  key: ENC(9zqDsgzBumBBJFnUI4WKLd8dJJWShdC1RAwwmDB/dRzneBDRCLJaxcMOI6k4bKNB7Q77+SzL+vluSmBmAXpMh8TUlrm10MYGfCiLfWmlWM6QMhNKDMa9F1o/+wAppUoGWG9e/Iv82D04cvExrD1aWg==)

logging:
  config: classpath:log/log4j2-${spring.profiles.active}.xml
#  level:
#    jdbc:
#      sqlonly: off
#      sqltiming: info
#      resultsettable: info
#      audit: off
#      resultset: off
#      connection: off

#---
#spring:
#  config:
#    activate:
#      on-profile:
#        - prod
#
#logging:
#  level:
#    jdbc:
#      resultsettable: off

#logging:
#  level:
#    com.example : DEBUG