spring:
  config:
    activate:
      on-profile:
        - test

  data:
    redis:
      host: localhost
      port: 16379

  flyway:
    enabled: false

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations:
        - classpath:sql/data.sql

cloud:
  aws:
    s3:
      root-dir: "test/"


jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    bean: jasyptStringEncryptor

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: TRACE