CREATE TABLE `curation`
(
    id           TINYINT PRIMARY KEY,
    magazine_id  BIGINT  UNIQUE NULL,
    updated_time DATETIME NOT NULL,
    FOREIGN KEY (`magazine_id`) REFERENCES `magazine` (`magazine_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;


INSERT INTO curation (id, magazine_id, updated_time)
SELECT 1, NULL, NOW()
UNION ALL
SELECT 2, NULL, NOW()
UNION ALL
SELECT 3, NULL, NOW()
UNION ALL
SELECT 4, NULL, NOW()
UNION ALL
SELECT 5, NULL, NOW()
UNION ALL
SELECT 6, NULL, NOW()
UNION ALL
SELECT 7, NULL, NOW()
UNION ALL
SELECT 8, NULL, NOW()
UNION ALL
SELECT 9, NULL, NOW()
UNION ALL
SELECT 10, NULL, NOW()
UNION ALL
SELECT 11, NULL, NOW()
UNION ALL
SELECT 12, NULL, NOW()
UNION ALL
SELECT 13, NULL, NOW()
UNION ALL
SELECT 14, NULL, NOW()
UNION ALL
SELECT 15, NULL, NOW()
UNION ALL
SELECT 16, NULL, NOW()
UNION ALL
SELECT 17, NULL, NOW()
UNION ALL
SELECT 18, NULL, NOW()
UNION ALL
SELECT 19, NULL, NOW()
UNION ALL
SELECT 20, NULL, NOW()
UNION ALL
SELECT 21, NULL, NOW()
UNION ALL
SELECT 22, NULL, NOW();

